# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/fuxi/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fuxi)

$(call add-radio-file-sha1-checked,radio/abl.img,de37ae2325a5fde9ed4e7566aba5de8e99acecfe)
$(call add-radio-file-sha1-checked,radio/aop.img,f1a36b7eee1c833d87e538dd1d1961cdde3b48ce)
$(call add-radio-file-sha1-checked,radio/aop_config.img,b14e887febf5177bacd45d485e7f3f0385a8ad61)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,f6e535037085fa58b1d080a0484a0ce5322d5ea3)
$(call add-radio-file-sha1-checked,radio/cpucp.img,38398f925a15a84511e896416437a9734bcf380b)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c745d3b385479a75e5d240f7da0dca7fe68b9329)
$(call add-radio-file-sha1-checked,radio/dsp.img,95df663a7212374cfe631af30b56b009f465d73a)
$(call add-radio-file-sha1-checked,radio/featenabler.img,f9d366a704422615f1b78a5efa768c4f175c93f7)
$(call add-radio-file-sha1-checked,radio/hyp.img,965ebcbca1ee26b43c14c993dc8c73cb2af65a90)
$(call add-radio-file-sha1-checked,radio/imagefv.img,7962a776344b8582dffecc684bcb90c671e6abd8)
$(call add-radio-file-sha1-checked,radio/keymaster.img,184cb080302f29e0b709aba365e03d109c79450f)
$(call add-radio-file-sha1-checked,radio/modem.img,c9bf25012b3e7a3d658f34d044e7e5b962b98340)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0ae5641bfb6bd861d70dea5a732fb6e4cc082cff)
$(call add-radio-file-sha1-checked,radio/shrm.img,179ff9414345bdde399cf3b078cc47963ae0a7a4)
$(call add-radio-file-sha1-checked,radio/tz.img,3701d9f0943b24c6dd58f97ff688015129ed1080)
$(call add-radio-file-sha1-checked,radio/uefi.img,c55dfa039948561b89ac526ec1de6120d57904aa)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,1fc28e1eaa43fd3548a845e17a58709ffbfde90d)
$(call add-radio-file-sha1-checked,radio/xbl.img,33fa607c9d92bccd85a1a537ee51cd21a5bc3756)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,26cfecc62da53b18b814408bf4ebd852d8f665e8)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,4e8c9883efd1a8cb877090f64b6625aa3e9fc301)

endif
